# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: phongphamthe/pipelines-dotnet-core
    endpoint: github.com_phongphamthe
    type: github
    name: phongphamthe/pipelines-dotnet-core
    ref: refs/heads/master

stages:

- stage: Build
  displayName: 'Build source code'
  condition: succeeded()
  jobs:
    - job: Checkout_and_Build_Job
      displayName: 'Checkout & Build Project'
      steps:
        - script: echo Use .NET $(dotnetVersion)
          displayName: Use .NET $(dotnetVersion)
        - script: echo Gitleaks enabled $(gitleaks_enabled) gitleaks__scanlocation $(gitleaks__scanlocation) gitleaks__configfile $(gitleaks__configfile) gitleaks__baselinePath $(gitleaks__baselinePath) gitleaks__reportfolder $(gitleaks__reportfolder) 
          displayName: Gitleaks enabled $(gitleaks_enabled)
        - checkout: self
          persistCredentials: true
          fetchDepth: 0
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
